---
- hosts: wind
  tasks:

    - name: Create folder
      win_file:
       path: C:\Users\Administrator\Desktop\ansible-windows
       mode: 0655
       state: directory
    - name: Download a package
      win_get_url:
        url: https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.14.tar.xz
        dest: C:\Users\Administrator\Desktop\ansible-windows
    - name: Install IIS
      win_feature:
        name: Web-server
        state: present
    - name: Ensure IIS is running 
      win_service:
        name: W3SVC  
        state: started     
    - name: Copy index file to windows server
      win_copy:
        src: index.html
        dest: C \ inetpub\wwwroot\index.html
